---
classes:
  - wso2brs
pack_filename: "%{::product_name}-%{::product_version}.zip"
pack_extracted_dir: "%{::product_name}-%{::product_version}"
template_list :
  - bin/wso2server.sh
  - repository/conf/axis2/axis2.xml
  - repository/conf/datasources/master-datasources.xml
  - repository/conf/tomcat/catalina-server.xml
  - repository/conf/carbon.xml
  - repository/conf/jndi.properties
  - repository/conf/registry.xml
  - repository/conf/user-mgt.xml
service_name: wso2brs
service_template: wso2base/wso2service.erb
file_list: []

ports :
  offset : 0

datasources :
  local_db :
    driver : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    user : wso2carbon
    password : wso2carbon
    securevault : false
    jndi_config : jdbc/WSO2CarbonDB
  config_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/config_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/config_db
  gov_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/gov_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/gov_db
  user_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/user_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/user_db

jvm:
  jvm_memory_xms: 256m
  jvm_memory_xmx: 1024m
  jvm_memory_max_perm_size: 256m

so_timeout: 600000
connection_timeout: 600000

clustering:
  enable: false
  membership_scheme: multicast
  local_member_host: 127.0.0.1
  local_member_port: 4000
  wka :
         members :
           -
             hostname : localhost
             port : 4000
           -
             hostname : localhost
             port : 4001


domain: wso2.carbon.domain
sub_domain: worker

dep_sync :
    enable : false
    auto_commit : false
    svn :
       url : http://svnrepo.example.com/repos/
       user : username
       password : password
