---
classes:
  - wso2brs
pack_filename: "%{::product_name}-%{::product_version}.zip"
pack_extracted_dir: "%{::product_name}-%{::product_version}"
template_list :
  - repository/conf/carbon.xml
  - bin/wso2server.sh
service_name: wso2brs
service_template: wso2base/wso2service.erb
file_list: []

ports :
  offset : 0

datasources :
  local_db :
    driver : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    user : wso2carbon
    password : wso2carbon
    securevault : false
    jndi_config : jdbc/WSO2CarbonDB
  config_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/config_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/config_db
  gov_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/gov_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/gov_db
  user_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/user_db?autoReconnect=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/user_db
  apimgt_db :
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/apimgt_db?autoReconnect=true&amp;relaxAutoCommit=true
    user : root
    password : root
    securevault : false
    jndi_config : jdbc/WSO2AM_DB

clustering :
    enable : false
    local_member_host : 127.0.0.1
    local_member_port : 4000
    membership_scheme : wka
    wka : 
       members : 
         - 
           hostname : localhost
           port : 4000
         -
           hostname : localhost
           port : 4001
    multicast :
       domain : wso2.carbon.domain
    k8s : 
    ppaas :

dep_sync :
    enable : false
    auto_commit : false
    svn :
       url : http://svnrepo.example.com/repos/
       user : username
       password : password
