---
classes:
  - wso2greg
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"
wso2::template_list :
  - repository/conf/axis2/axis2.xml
  - repository/conf/carbon.xml
  - repository/conf/registry.xml
  - repository/conf/datasources/master-datasources.xml
  - repository/conf/tomcat/catalina-server.xml
  - bin/wso2server.sh
wso2::service_name: wso2greg
wso2::service_template: wso2base/wso2service.erb
wso2::file_list: []

wso2::ports:
  mapping :
    "9763" : 8280
    "9443" : 8243

wso2::clustering :
    enable : false
    local_member_host : 127.0.0.1
    local_member_port : 4000
    membership_scheme : wka
    wka :
       members :
         -
           hostname : localhost
           port : 4000
         -
           hostname : localhost
           port : 4001
    multicast :
       domain : wso2.carbon.domain
    k8s :
    ppaas :

wso2::master_datasources :
  WSO2AM_DB :
    description : The datasource used for API Manager database
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : wso2carbon
    password : wso2carbon
    #securevault :
    jndi_config : jdbc/WSO2AM_DB
    maxActive : "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait : "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow : "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery : "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval : "%{hiera('wso2::datasources::common::validationInterval')}"
  WSO2BAM_DATASOURCE :
    description : The datasource used for analyzer data
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/samples/BAM_STATS_DB;AUTO_SERVER=TRUE
    username : wso2carbon
    password : wso2carbon
    #securevault :
    jndi_config : jdbc/WSO2BAM_DATASOURCE
    maxActive : "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait : "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow : "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery : "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval : "%{hiera('wso2::datasources::common::validationInterval')}"
  JAGH2 :
    description : The datasource used for by the Jaggery Storage Manager
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/ES_STORAGE;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : sa
    password : 
    #securevault :
    jndi_config : jdbc/test
    maxActive : "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait : "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow : "%{hiera('wso2::datasources::common::testOnBorrow')}"
    validationQuery : "%{hiera('wso2::datasources::mysql::validationQuery')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationInterval : "%{hiera('wso2::datasources::common::validationInterval')}"
  WSO2_CONFIG_DB :
    description : The datasource used for config registry
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2_CONFIG_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : wso2carbon
    password : wso2carbon
    #securevault :
    jndi_config : jdbc/WSO2_CONFIG_DB
    maxActive : "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait : "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow : "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery : "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval : "%{hiera('wso2::datasources::common::validationInterval')}"
    mount :
     enabled : false
     path : /_system/config
     target_path : /_system/config
  WSO2_GOV_DB :
    description : The datasource used for gov registry
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2_GOV_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : wso2carbon
    password : wso2carbon
    #securevault : false
    jndi_config : jdbc/WSO2_GOV_DB
    maxActive: "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait: "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow: "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery: "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval: "%{hiera('wso2::datasources::common::validationInterval')}"
    mount :
     enabled : false
     path : /_system/gov
     target_path : /_system/gov
