---
classes:
  - wso2mb
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"

wso2::service_name: wso2mb
wso2::hostname : mb.wso2.com

wso2::template_list :
  - repository/conf/broker.xml

wso2::mb_thrift_port : 7611

wso2::master_datasources :
  wso2_mb_store_db :
      name : WSO2_MB_STORE_DB
      description : The datasource used for message broker database
      driver_class_name : org.h2.Driver
      url : jdbc:h2:repository/database/WSO2MB_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
      username : "%{hiera('wso2::datasources::common::username')}"
      password : "%{hiera('wso2::datasources::common::password')}"
      #secretAlias :
      jndi_config : WSO2MBStoreDB
      max_active : "%{hiera('wso2::datasources::common::max_active')}"
      max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
      test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
      default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
      validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
      validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"


