---
classes:
  - wso2am
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"
wso2::template_list :
  - repository/conf/carbon.xml
  - repository/conf/user-mgt.xml
  - repository/conf/registry.xml
  - repository/conf/datasources/am-datasources.xml
  - repository/conf/datasources/master-datasources.xml
  - repository/conf/tomcat/catalina-server.xml
  - repository/conf/axis2/axis2.xml
  - bin/wso2server.sh

wso2::service_name: wso2am
wso2::service_template: wso2base/wso2service.erb
wso2::file_list : []
wso2::clustering :
    enabled : false
    local_member_host : 127.0.0.1
    local_member_port : 4000
    membership_scheme : wka
    wka :
       members :
         -
           hostname : localhost
           port : 4000
         -
           hostname : localhost
           port : 4001
    multicast :
       domain : wso2.carbon.domain
    k8s :
    ppaas :

#wso2::ports:
#  proxyPort :
#    http: 80
#    https: 443

#wso2::registry_mounts:
#  WSO2_CONFIG_DB:
#    path: /_system/config
#    target_path: /_system/config
#    readOnly: true
#    registryRoot: /
#    enableCache: true
#
#  WSO2_GOV_DB:
#    path: /_system/gov
#    target_path: /_system/gov
#    readOnly: true
#    registryRoot: /
#    enableCache: true

#wso2::usermgt_datasource: WSO2USER_DB

wso2::am_datasources :
  WSO2AM_DB:
    description: The datasource used for API Manager database
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE
    username : "%{hiera('wso2::datasources::common::username')}"
    password : "%{hiera('wso2::datasources::common::password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2AM_DB
    maxActive: "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait: "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow: "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit: "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery: "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval: "%{hiera('wso2::datasources::common::validationInterval')}"

wso2::master_datasources :
  WSO2_CONFIG_DB:
    description: The datasource used for config registry
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2_CONFIG_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : "%{hiera('wso2::datasources::common::username')}"
    password : "%{hiera('wso2::datasources::common::password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2_CONFIG_DB
    maxActive: "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait: "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow: "%{hiera('wso2::datasources::common::testOnBorrow')}"
    validationQuery: "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval: "%{hiera('wso2::datasources::common::validationInterval')}"

  WSO2_GOV_DB:
    description: The datasource used for gov registry
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2_GOV_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : "%{hiera('wso2::datasources::common::username')}"
    password : "%{hiera('wso2::datasources::common::password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2_GOV_DB
    maxActive: "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait: "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow: "%{hiera('wso2::datasources::common::testOnBorrow')}"
    validationQuery: "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval: "%{hiera('wso2::datasources::common::validationInterval')}"

  WSO2USER_DB :
    description : The datasource is used for user mangement and userstore
    driverClassName : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2USER_DB?autoReconnect=true
    username : "%{hiera('wso2::datasources::common::username')}"
    password : "%{hiera('wso2::datasources::common::password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2USER_DB
    maxActive : "%{hiera('wso2::datasources::common::maxActive')}"
    maxWait : "%{hiera('wso2::datasources::common::maxWait')}"
    testOnBorrow : "%{hiera('wso2::datasources::common::testOnBorrow')}"
    defaultAutoCommit : "%{hiera('wso2::datasources::common::defaultAutoCommit')}"
    validationQuery : "%{hiera('wso2::datasources::mysql::validationQuery')}"
    validationInterval : "%{hiera('wso2::datasources::common::validationInterval')}"
