---
classes:
  - wso2bps
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"
wso2::template_list :
        - bin/wso2server.sh
        - repository/conf/axis2/axis2.xml
#        - repository/conf/datasources/activiti-datasources.xml
#        - repository/conf/datasources/bps-datasources.xml
#        - repository/conf/datasources/master-datasources.xml
        - repository/conf/tomcat/catalina-server.xml
#        - repository/conf/activiti.xml
        - repository/conf/bps.xml
        - repository/conf/carbon.xml
        - repository/conf/humantask.xml
        - repository/conf/jndi.properties
#        - repository/conf/registry.xml
#        - repository/conf/user-mgt.xml
wso2::service_name: wso2bps
wso2::service_template: wso2base/wso2service.erb
wso2::file_list: []

wso2::jvm:
  jvm_memory_xms: 256m
  jvm_memory_xmx: 1024m
  jvm_memory_max_perm_size: 256m

wso2::so_timeout: 600000
wso2::connection_timeout: 600000

wso2::clustering:
  enable: false
  membership_scheme: multicast
  local_member_host: 127.0.0.1
  local_member_port: 4000
  wka :
         members :
           -
             hostname : localhost
             port : 4000
           -
             hostname : localhost
             port : 4001


wso2::domain: wso2.carbon.domain
wso2::sub_domain: worker

wso2::mex_timeout: 600000
wso2::external_service_timeout: 600000
wso2::max_connections_per_host: 350
wso2::max_total_connections: 400
wso2::ode_scheduler_thread_pool_size: 50
wso2::scheduler_config_max_thread_pool_size: 50
wso2::enable_humantask_caching: false
wso2::http_proxy_port: "%{::http_proxy_port}"
wso2::https_proxy_port: "%{::https_proxy_port}"

wso2::datasources :
  config_db :
      driver :
      url :
      user :
      password :
      securevault :
      jndi_config :
  gov_db :
      driver :
      url :
      user :
      password :
      securevault :
      jndi_config :
  user_db :
      driver :
      url :
      user :
      password :
      securevault :
      jndi_config :
  local_db :
      driver :
      url :
      user :
      password :
      securevault:
      jndi_config :
  bps_ds_db :
      driver :
      url :
      user :
      password :
      securevault:
      jndi_config :
  activiti_db :
      driver :
      url :
      user :
      password :
      securevault:
      jndi_config :