# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wso2::hostname: wso2am-api-publisher
wso2::mgt_hostname: wso2am-api-publisher

wso2::apim_gateway:
    host: wso2am-gateway-manager

wso2::apim_keymanager:
    host: wso2am-api-key-manager

wso2::apim_store:
    host: wso2am-api-store
    port: 32019

wso2::apim_publisher:
    host: wso2am-api-publisher
    port: 32017

wso2::clustering:
    enabled: true
    membership_scheme: kubernetes
    kubernetes:
       kubernetes_namespace: default
       kubernetes_services: wso2am-api-publisher,wso2am-api-store

wso2::file_list:
  - repository/components/lib/jackson-annotations-2.5.4.jar
  - repository/components/lib/jackson-core-2.5.4.jar
  - repository/components/lib/jackson-databind-2.5.4.jar
  - repository/components/lib/kubernetes-membership-scheme-1.0.0-SNAPSHOT.jar

wso2::ports:
  proxyPort:
    http: 32016
    https: 32017

wso2::registry_mounts:
  wso2_config_db:
    path: /_system/config
    target_path: /_system/config/api-publisher
    read_only: false
    registry_root: /
    enable_cache: true
  wso2_gov_db:
    path: /_system/governance
    target_path: /_system/governance
    read_only: false
    registry_root: /
    enable_cache: true
